language: crystal

crystal:
  - latest

script:
  - crystal spec
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: toddsundsted/ishi
  on:
    branch: main
  local_dir: docs
